services:
  - type: web
    name: microroulette-linera
    env: docker
    dockerfilePath: ./Dockerfile.railway
    plan: free
    region: oregon
    envVars:
      - key: LINERA_FAUCET_URL
        value: https://faucet.testnet-conway.linera.net
      - key: APP_ID
        value: 9b16ccbe34c686f959ad6d3ebe9dde35a1ab7cf73a99a470feae0b082be59059
      - key: CHAIN_ID
        value: 781078b5a05e20fb1cd13c06622ccc91f813d112f020816e799a9ec1ba4298dc
      - key: LINERA_SERVICE_PORT
        value: 8082
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 8082
    healthCheckPath: /
